### PR TITLE
Support loading of folder path

### PR DESCRIPTION
**Pull request by bschrag620**
* adds load_directory method in registry
* redirects load method to load_directory if the pathname is recognized as a directory
* adds supporting tests for folder loading

### CODE REVIEW

**Comment by joeldrapper** [comment]
A practical example of this, I’m trying to run some tests in isolation from Rails while other tests depend on it. I structured my tests with two root folders: `test/isolated` and `test/rails`, where “isolated” tests never require Rails.

I was able to run these separately on my Mac using globs:

`bundle exec sus test/rails/**/*rb && bundle exec sus test/isolated/**/*rb`

However, these globs do not seem to work in other environments such as GitHub Actions. This PR makes it possible to run `bundle exec sus test/rails && bundle exec sus test/isolated`, which would solve that problem for me.

**Comment by bschrag** [comment]
> I was able to run these separately on my Mac using globs

I'm running Ubuntu on WSL and can confirm the error. Ubuntu seems to handle the glob pattern in a way that excludes current folder from the selection path. This leads to an error if there are no subfolders since no files are found.

**Comment by bschrag620** [comment]
> I was able to run these separately on my Mac using globs

I'm running Ubuntu on WSL and can confirm the error. Ubuntu seems to handle the glob pattern in a way that excludes current folder from the selection path. This leads to an error if there are no subfolders since no files are found.

**Comment by ioquatix** [comment]
I need some time to think about this. It might be better to use a filter and/or provide some kind of tagging functionality.

**Comment by joeldrapper** [comment]
Makes sense. Have you considered other ways to isolate tests from dependencies? I've been trying to find a good way to do this.

Sometimes it might be an option to `private_constant` a dependency while executing a test. But with Rails, there are so many patches you could inadvertently depend on it's best to run the tests in an environment where it's not been loaded.

**Pull request merged**
